import { StyleSheet } from 'react-native';
import { Brand } from '@/constants/Brand';

export const estiloFormulario = StyleSheet.create({
  editContainer: { flex: 1, backgroundColor: Brand.background },
  editHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: Brand.card,
    borderBottomWidth: 1,
    borderBottomColor: Brand.border,
  },
  editHeaderTitulo: { fontSize: 16, fontWeight: '700', color: Brand.textPrimary },
  editScroll: { padding: 16, paddingBottom: 32, gap: 12 },
  editCapaWrapper: { alignItems: 'center', marginBottom: 4 },
  editCapa: { width: 100, height: 140, borderRadius: 12, backgroundColor: Brand.placeholder },
  editCapaPlaceholder: { alignItems: 'center', justifyContent: 'center' },
  editCapaAviso: { fontSize: 11, color: Brand.textSecondary, textAlign: 'center', marginBottom: 8 },
  editCard: { backgroundColor: Brand.card, borderRadius: 16, padding: 16, gap: 4 },
  campoLabel: { fontSize: 12, fontWeight: '600', color: Brand.textTertiary, marginTop: 12, marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: Brand.textPrimary,
  },
  inputDesabilitado: { backgroundColor: '#f1f5f9' },
  linhaDupla: { flexDirection: 'row', gap: 12 },
  selectBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  selectTexto: { fontSize: 14, color: Brand.textPrimary },
  selectOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', padding: 32 },
  selectLista: { backgroundColor: '#fff', borderRadius: 14, paddingVertical: 8, maxHeight: 340, overflow: 'hidden' },
  selectItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  selectItemTexto: { fontSize: 14, color: Brand.textPrimary },
  selectItemTextoAtivo: { color: Brand.primary, fontWeight: '700' },
  estrelas: { flexDirection: 'row', gap: 6 },
  avaliacaoBloqueada: { fontSize: 12, color: Brand.textSecondary, fontStyle: 'italic' },
  editRodape: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    backgroundColor: Brand.card,
    borderTopWidth: 1,
    borderTopColor: Brand.border,
  },
  botaoCancelar: { flex: 1, borderRadius: 10, paddingVertical: 13, alignItems: 'center', backgroundColor: '#f1f5f9' },
  botaoCancelarTexto: { fontSize: 14, fontWeight: '700', color: Brand.textTertiary },
  botaoSalvar: { flex: 2, borderRadius: 10, paddingVertical: 13, alignItems: 'center', backgroundColor: Brand.primary },
  botaoSalvarTexto: { fontSize: 14, fontWeight: '700', color: '#fff' },
});
